✨ First implementation with simple proxying
approvers/contacts-gateway pull request #2
Opened 2020-07-24 14:55 UTC by Siketyan

- `/twitter/{id}`
- `/github/{id}`
- `/discord/{id}`

2020-07-24 14:57 UTC, Siketyan commented
No caching is here ... yet.

2020-07-24 15:58 UTC, MikuroXina requested changes

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Services/Fetchers/IFetcher.cs
> +        public Task<T> FetchAsync(ulong id);
```suggestion
        Task<T> FetchAsync(ulong id);
```

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Models/Contacts/IContact.cs
> +        public string Url { get; set; }
```suggestion
        ulong Id { get; set; }
        string Name { get; set; }
        string Url { get; set; }
```

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Models/Contacts/DiscordContact.cs
> +        public string Tag { get; set; }
`set;` が付いている理由がわかりません (他の `Contact` らも同様)

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Controllers/GitHubController.cs
> +        }
これ存在しない `id` が渡された場合のエラーハンドリングってどうなってますか?

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Services/Fetchers/TwitterFetcher.cs
> +            );
こちらも `GitHubFetcher` と同じように `interface GitHubClient` を追加した方がテスト性などで好ましいかと思います

2020-07-24 15:58 UTC, MikuroXina commented on ContactsGateway/Services/Fetchers/GitHubFetcher.cs
> +        public GitHubFetcher(GitHubClient client)
`GitHubClient` は `interface` にしておいた方がいいと思います

2020-07-24 23:56 UTC, Siketyan commented on ContactsGateway/Models/Contacts/DiscordContact.cs
> +        public string Tag { get; set; }
GitHubClient で使ってる JSON パーサが set つけないと値を入れてくれないので、、、

2020-07-25 04:40 UTC, MikuroXina commented on ContactsGateway/Models/Contacts/DiscordContact.cs
> +        public string Tag { get; set; }
`GitHubClient` については承知しました。この `DiscordContact` の場合はなぜですか?

2020-07-25 04:57 UTC, Siketyan commented on ContactsGateway/Models/Contacts/DiscordContact.cs
> +        public string Tag { get; set; }
たしかに（たしかに）
削除します……

2020-07-25 12:43 UTC, Siketyan commented on ContactsGateway/Models/Contacts/IContact.cs
> +        public string Url { get; set; }
07b4980

2020-07-25 12:43 UTC, Siketyan commented on ContactsGateway/Services/Fetchers/IFetcher.cs
> +        public Task<T> FetchAsync(ulong id);
07b4980

2020-07-25 12:49 UTC, Siketyan commented on ContactsGateway/Services/Fetchers/GitHubFetcher.cs
> +        public GitHubFetcher(GitHubClient client)
c0336dd

2020-07-25 13:08 UTC, Siketyan commented on ContactsGateway/Services/Fetchers/TwitterFetcher.cs
> +            );
85aacb8, ce2d29d

2020-07-25 13:11 UTC, Siketyan commented on ContactsGateway/Models/Contacts/DiscordContact.cs
> +        public string Tag { get; set; }
fa15624

2020-07-25 13:13 UTC, MikuroXina commented on ContactsGateway/Controllers/GitHubController.cs
> +        }
例えば、存在しないなら `404` を返すといった処理のことです
おそらく `Startup.cs` で書くものだとは思いますが

2020-07-25 13:14 UTC, Siketyan commented on ContactsGateway/Controllers/GitHubController.cs
> +        }
各 Fetcher で ContactNotFoundException をスローするほうがいいかな……と思ってます

2020-07-25 13:46 UTC, Siketyan commented on ContactsGateway/Controllers/GitHubController.cs
> +        }
d1762f1

2020-07-25 14:13 UTC, MikuroXina requested changes

2020-07-25 14:13 UTC, MikuroXina commented on ContactsGateway/Controllers/DiscordController.cs
> +            catch (ContactNotFoundException<DiscordContact> _)
```suggestion
            catch (ContactNotFoundException<DiscordContact>)
```

2020-07-25 15:32 UTC, Siketyan commented on ContactsGateway/Controllers/DiscordController.cs
> +            catch (ContactNotFoundException<DiscordContact> _)
他の言語やりすぎてそれができるの完全に忘れてた
ab661b3

2020-07-25 15:35 UTC, MikuroXina approved these changes

2020-07-25 15:36 UTC, merged